services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /data
  project-issue-svc:
    build:
      context: .
      dockerfile: src/ProjectIssueService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres;User Id=postgres;Password=postgrespw;Database=projecttasks
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7003:80
    depends_on:
      - rabbitmq
      - postgres
  identity-svc:
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres; User Id=postgres; Password=postgrespw; Database=identity
    ports:
      - 5000:80
    depends_on:
      - postgres
  gateway-svc:
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=http://localhost:3000
    ports:
      - 6001:80
  user-svc:
    build:
      context: .
      dockerfile: src/UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres;User Id=postgres;Password=postgrespw;Database=users
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7004:80
    depends_on:
      - rabbitmq
      - postgres
  issue-stats-svc:
    build:
      context: .
      dockerfile: src/IssueStatsService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - Redis__Host=redis
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7005:80
    depends_on:
      - rabbitmq
      - redis
      - postgres
