services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /data
  project-issue-svc:
    image: w6731827/project-issue-svc:latest
    build:
      context: .
      dockerfile: src/ProjectIssueService/Dockerfile
    env_file:
      - ./src/ProjectIssueService/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres;User Id=postgres;Password=postgrespw;Database=projecttasks
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7003:80
    depends_on:
      - rabbitmq
      - postgres
  identity-svc:
    image: w6731827/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - IssuerUri=http://localhost:5000
      - ClientApp=http://localhost:3000
      - ConnectionStrings__DefaultConnection=Server=postgres; User Id=postgres; Password=postgrespw; Database=identity
    ports:
      - 5000:80
    depends_on:
      - postgres
  gateway-svc:
    image: w6731827/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=http://localhost:3000
    ports:
      - 6001:80
  user-svc:
    image: w6731827/user-svc:latest
    build:
      context: .
      dockerfile: src/UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres;User Id=postgres;Password=postgrespw;Database=users
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7004:80
    depends_on:
      - rabbitmq
      - postgres
  issue-stats-svc:
    image: w6731827/issue-stats-svc:latest
    build:
      context: .
      dockerfile: src/IssueStatsService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMQ__Host=rabbitmq
      - Redis__Host=redis
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7005:80
    depends_on:
      - rabbitmq
      - redis
      - postgres
  web-app:
    image: w6731827/web-app:latest
    build:
      context: .
      dockerfile: frontend/web-app/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /var/lib/web/data
    environment:
      - AUTH_SECRET="secret"
      - AUTH_URL=http://localhost:3000
      - AUTH_URL_INTERNAL=http://web-app:3000
      - API_URL_INTERNAL=http://gateway-svc/api
      - ID_URL=http://localhost:5000
      - ID_URL_INTERNAL=http://identity-svc
