apiVersion: v1
kind: ConfigMap
metadata:
  name: project-issue-svc-config
data:
  ASPNETCORE_URLS: http://+:80;
  RabbitMQ__Host: rabbit-clusterip
  IdentityServiceUrl: http://identity-clusterip
  Kestrel__Endpoints__WebApi__Protocols: Http1
  Kestrel__Endpoints__WebApi__Url: http://+:80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-svc-config
data:
  ASPNETCORE_URLS: http://+:80;
  RabbitMQ__Host: rabbit-clusterip
  IdentityServiceUrl: http://identity-clusterip
  Kestrel__Endpoints__WebApi__Protocols: Http1
  Kestrel__Endpoints__WebApi__Url: http://+:80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: issue-stats-svc-config
data:
  ASPNETCORE_URLS: http://+:80;
  RabbitMQ__Host: rabbit-clusterip
  IdentityServiceUrl: http://identity-clusterip
  Kestrel__Endpoints__WebApi__Protocols: Http1
  Kestrel__Endpoints__WebApi__Url: http://+:80
  Redis__Host: redis-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  ClientApp: https://app.issuetracker.local
  IdentityServiceUrl: http://identity-clusterip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-svc-config
data:
  ASPNETCORE_URLS: http://+:80
  IssuerUri: https://id.issuetracker.local
  ClientApp: https://app.issuetracker.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-svc-config
data:
  AUTH_URL: https://app.issuetracker.local
  AUTH_URL_INTERNAL: http://webapp-clusterip:3000
  API_URL_INTERNAL: http://gateway-clusterip/api
  ID_URL: https://id.issuetracker.local
  ID_URL_INTERNAL: http://identity-clusterip
