apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: postgrespw
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
stringData:
  username: rabbit
  password: rabbitpw
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData:
  password: redis_password
---
apiVersion: v1
kind: Secret
metadata:
  name: project-issue-secret
type: Opaque
stringData:
  connString: Server=postgres-clusterip;User Id=postgres;Password=postgrespw;Database=projectissues
---
apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: Opaque
stringData:
  connString: Server=postgres-clusterip;User Id=postgres;Password=postgrespw;Database=users
---
apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
type: Opaque
stringData:
  connString: Server=postgres-clusterip;User Id=postgres;Password=postgrespw;Database=identity
  userDefaultPassword: Pass123$
---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
stringData:
  authSecret: secret
